//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pruebasodimac.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAR_CENTEREntities : DbContext
    {
        public CAR_CENTEREntities()
            : base("name=CAR_CENTEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<documento> documento { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<mecanico> mecanico { get; set; }
        public virtual DbSet<repuestos> repuestos { get; set; }
        public virtual DbSet<servicios> servicios { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<mantenimiento> mantenimiento { get; set; }
    }
}
