//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pruebasodimac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantenimiento
    {
        public int id_manten { get; set; }
        public Nullable<int> num_unidades { get; set; }
        public Nullable<decimal> precio_unidad { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public int id_repuesto { get; set; }
        public int id_mecanico { get; set; }
        public int id_servicio { get; set; }
        public Nullable<int> id_cliente { get; set; }
    
        public virtual mecanico mecanico { get; set; }
        public virtual repuestos repuestos { get; set; }
        public virtual servicios servicios { get; set; }
        public virtual cliente cliente { get; set; }
    }
}
